name: Notify Slack on PR and master merge

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify on Pull Request
        if: github.event_name == 'pull_request'
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":bell: *New Pull Request!* :bell:\nRepository: <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>\nAuthor: *${{ github.actor }}*\nPR: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on Merge to master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":rocket: *Changes merged to master!* :rocket:\nRepository: <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>\nPushed by: *${{ github.actor }}*\nCommit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
